version: '3'

services:
  proxy:
    image: proxynginx 
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: firstapp  # this will use httpd:latest
